---
- name: "MacOSX | Install"
  community.general.homebrew:
    name: visual-studio-code
- name: "MacOSX | Enable key repeating for Vim plugin"
  community.general.osx_defaults:
    domain: com.microsoft.VSCode
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
    state: present
