---
- name: "MacOSX : Install"
  community.general.homebrew:
    name: ghostty
- name: "MacOSX : Create ghostty config directory"
  ansible.builtin.file:
    path: "{{ ghostty_config_path }}"
    state: directory
    mode: "0755"
- name: "MacOSX : Link config"
  ansible.builtin.file:
    src: "{{ role_path }}/files/ghostty/config"
    dest: "{{ ghostty_config_path }}/config"
    state: link
    force: true
