---
- name: "MacOSX : Install"
  community.general.homebrew:
    name: ghostty
- name: "MacOSX : Link config"
  ansible.builtin.file:
    src: "{{ role_path }}/files/ghostty/config"
    dest: "{{ ansible_user_dir }}/.config/ghostty/config"
    state: link
    force: true
