---
- name: "MacOSX | Install"
  community.general.homebrew:
    name: ghostty
- name: "MacOSX | Copy config"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/"
    src: "ghostty"
    directory_mode: "u=rwx,g=rx,o=rx"
    mode: "u=rw,g=r,o=r"
